name: Build Rosé Plugin for development and checks

on: push

jobs:
    build-plugin:
        name: Build Rosé Plugin
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: Build Toolchain Container
              run: docker build . -t builder
            - uses: ammaraskar/gcc-problem-matcher@master
            - name: Build Plugin
              run: docker run --rm -v ${PWD}:/app -w /app builder
            - uses: actions/upload-artifact@master
              with:
                  name: devbuild
                  path: "*.wps"
